const SerialDataProducts = [
    { Model: "FDX60M2", numOfFibers: "2", fiber: "Multimode", optics: "ST", package: "ComFit" },
    { Model: "FDX60M2M", numOfFibers: "2", fiber: "Multimode", optics: "ST", package: "Compact" },
    { Model: "FDX60M2/SC", numOfFibers: "2", fiber: "Multimode", optics: "SC", package: "ComFit" },
    { Model: "FDX60M2M/SC", numOfFibers: "2", fiber: "Multimode", optics: "SC", package: "Compact" },
    { Model: "FDX60S2", numOfFibers: "2", fiber: "Single mode", optics: "ST", package: "ComFit" },
    { Model: "FDX60S2M", numOfFibers: "2", fiber: "Single mode", optics: "ST", package: "Compact" },
    { Model: "FDX60S2/SC", numOfFibers: "2", fiber: "Single mode", optics: "SC", package: "ComFit" },
    { Model: "FDX60S2M/SC", numOfFibers: "2", fiber: "Single mode", optics: "SC", package: "Compact" },
    { Model: "FDX60M1A", numOfFibers: "1", fiber: "Multimode", optics: "ST", package: "ComFit" },
    { Model: "FDX60M1AM", numOfFibers: "1", fiber: "Multimode", optics: "ST", package: "Compact" },
    { Model: "FDX60M1A/SC", numOfFibers: "1", fiber: "Multimode", optics: "SC", package: "ComFit" },
    { Model: "FDX60M1AM/SC", numOfFibers: "1", fiber: "Multimode", optics: "SC", package: "Compact" },
    { Model: "FDX60SM1A", numOfFibers: "1", fiber: "Single mode", optics: "ST", package: "ComFit" },
    { Model: "FDX60S1AM", numOfFibers: "1", fiber: "Single mode", optics: "ST", package: "Compact" },
    { Model: "FDX60S1A/SC", numOfFibers: "1", fiber: "Single mode", optics: "SC", package: "ComFit" },
    { Model: "FDX60S1AM/SC", numOfFibers: "1", fiber: "Single mode", optics: "SC", package: "Compact" },
    { Model: "FDX60M1B", numOfFibers: "1", fiber: "Multimode", optics: "ST", package: "ComFit" },
    { Model: "FDX60M1BM", numOfFibers: "1", fiber: "Multimode", optics: "ST", package: "Compact" },
    { Model: "FDX60M1B/SC", numOfFibers: "1", fiber: "Multimode", optics: "SC", package: "ComFit" },
    { Model: "FDX60M1BM/SC", numOfFibers: "1", fiber: "Multimode", optics: "SC", package: "Compact" },
    { Model: "FDX60SM1B", numOfFibers: "1", fiber: "Single mode", optics: "ST", package: "ComFit" },
    { Model: "FDX60S1BM", numOfFibers: "1", fiber: "Single mode", optics: "ST", package: "Compact" },
    { Model: "FDX60S1B/SC", numOfFibers: "1", fiber: "Single mode", optics: "SC", package: "ComFit" },
    { Model: "FDX60S1BM/SC", numOfFibers: "1", fiber: "Single mode", optics: "SC", package: "Compact" },
  ];

export default SerialDataProducts;